
<?php
echo $_SERVER['SERVER_ADDR'];
echo $_SERVER['SERVER_NAME'];
echo $_SERVER['SERVER_SOFTWARE'];
echo $_SERVER['SERVER_PROTOCOL'];
echo $_SERVER['REQUEST_METHOD'];
echo $_SERVER['REQUEST_TIME'];
echo $_SERVER['REQUEST_TIME_FLOAT'];
echo $_SERVER['QUERY_STRING'];

?>
